# Server
server.port=8080

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/examportal?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=vansh
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false

# Email (Gmail SMTP - update with your credentials)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vanshsoni698@gmail.com
spring.mail.password=xghe dbbx qvrc rblp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# App
app.name=ExamPortal
